version: '3'

services:
  elasticsearch:
    image: elasticsearch:5.2.0
    command: elasticsearch -Enetwork.host=0.0.0.0
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  logstash:
    image: logstash:5.2.0
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    restart: always
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
      - "12201:12201"
      - "12201:12201/udp"
    links:
      - elasticsearch
  kibana:
    image: kibana:5.2.0
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  elasticsearch:
