elasticsearch:
  image: elasticsearch:5.1.2
  command: elasticsearch -Enetwork.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - elasticsearch1:/usr/share/elasticsearch/data
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
  ports:
    - "5000:5000"
    - "12201:12201"
    - "12201:12201/udp"
  links:
    - elasticsearch
kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
